version: '3.7'

services:
  omgwtfssl:
    image: paulczar/omgwtfssl
    restart: "no"
    volumes:
      - ${SERVER_HTTPS_CERT_VOLUME}:/certs:z
    environment:
      - SSL_SUBJECT=servhostname.local
      - CA_SUBJECT=my@example.com
      - SSL_KEY=/certs/servhostname.local.key
      - SSL_CSR=/certs/servhostname.local.csr
      - SSL_CERT=/certs/servhostname.local.crt
    # networks:
    #   - proxy-tier

volumes:
  certs:
